services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: POSTGRES_HOST
        fromDatabase:
          name: db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: db
          property: port
      - key: POSTGRES_DB
        fromDatabase:
          name: db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: db
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis
          property: port
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token_here  # Replace later
      - key: GOOGLE_API_KEY
        value: your_gemini_key_here
      # Add other env vars similarly

  - type: static
    name: frontend
    buildCommand: ""  # No build needed for static
    staticPublishPath: ./frontend
    plan: free

databases:
  - name: db
    plan: free  # Starter plan

redis:
  - name: redis
    plan: free