# fly.toml app configuration file generated for backend-damp-glade-3274 on 2025-08-16T14:04:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-damp-glade-3274'
primary_region = 'ams'

[build]



[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8080"

[deploy]
release_command = "alembic upgrade head"
