"""Add created_at field to decks table

Revision ID: 002
Revises: a2a71e08662a
Create Date: 2025-08-28 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '002'
down_revision = 'a2a71e08662a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'created_at')
    # ### end Alembic commands ###